CREATE DATABASE DB_VENDAS;
USE DB_VENDAS;
CREATE TABLE TB_FORNECEDOR (
	CD_FORNECEDOR INT NOT NULL AUTO_INCREMENT,
	NM_FORNECEDOR VARCHAR(255) NOT NULL,
    DS_EMAIL VARCHAR(255) NOT NULL,
    DS_RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    DS_CNPJ VARCHAR(255) NOT NULL,
   PRIMARY KEY(CD_FORNECEDOR)
   );
   
   CREATE TABLE TB_PRODUTO(
   CD_PRODUTO INT NOT NULL AUTO_INCREMENT,
   NM_PRODUTO VARCHAR(255) NOT NULL,
   CD_FORNECEDOR INT,
   primary key(CD_PRODUTO),
    FOREIGN KEY (CD_FORNECEDOR) REFERENCES TB_FORNECEDOR(CD_FORNECEDOR)
   );
   SELECT * FROM TB_FORNECEDOR
   SELECT * FROM TB_PRODUTO
   
   SELECT TB_PRODUTO.NM_PRODUTO, TB_FORNECEDOR.NM_FORNECEDOR, TB_FORNECEDOR.DS_RAZAO_SOCIAL  FROM TB_PRODUTO 
INNER JOIN TB_FORNECEDOR ON TB_FORNECEDOR.CD_FORNECEDOR = TB_PRODUTO.CD_FORNECEDOR
   
INSERT INTO TB_PRODUTO(NM_PRODUTO, CD_FORNECEDOR)
VALUES ('Sabão', 4);
