CREATE TABLE TB_FORNECEDOR (
	CD_FORNECEDOR INT NOT NULL AUTO_INCREMENT,
	NM_FORNECEDOR VARCHAR(255) NOT NULL,
    DS_EMAIL VARCHAR(255) NOT NULL,
    DS_RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    DS_CNPJ VARCHAR(255) NOT NULL,
   PRIMARY KEY(CD_FORNECEDOR)
   );
   
    ----  INSERT INTO TB_FORNECEDOR VALUES (1,'Alpagartas','alpagartas@teste.com', 'alpagartas havaiana','111');